/// Flag emoji from an ISO alpha-3 code via an alpha3→alpha2 map; unknown or
/// non-ISO codes (Somaliland, Zanzibar…) get 🌍.
String flagFromIso(String iso3) {
  const special = {
    'ABW': 'AW', 'AIA': 'AI', 'ALB': 'AL', 'AND': 'AD', 'ARM': 'AM',
    'ASM': 'AS', 'AZE': 'AZ', 'BMU': 'BM', 'CYM': 'KY', 'COK': 'CK',
    'CUW': 'CW', 'ESH': 'EH', 'FRO': 'FO', 'GIB': 'GI', 'GLP': 'GP',
    'GRL': 'GL', 'GUF': 'GF', 'GUM': 'GU', 'IMN': 'IM', 'MAC': 'MO',
    'MAF': 'MF', 'MNP': 'MP', 'MSR': 'MS', 'MTQ': 'MQ', 'NCL': 'NC',
    'NIU': 'NU', 'PRI': 'PR', 'PYF': 'PF', 'REU': 'RE', 'SHN': 'SH',
    'SXM': 'SX', 'TCA': 'TC', 'TKL': 'TK', 'UVK': 'XK', 'VGB': 'VG',
    'VIR': 'VI', 'WLF': 'WF', 'XKX': 'XK',
    'AFG': 'AF', 'AGO': 'AO', 'ARE': 'AE', 'ARG': 'AR', 'ATG': 'AG',
    'AUS': 'AU', 'AUT': 'AT', 'BDI': 'BI', 'BEL': 'BE', 'BEN': 'BJ',
    'BFA': 'BF', 'BGD': 'BD', 'BGR': 'BG', 'BHR': 'BH', 'BHS': 'BS',
    'BIH': 'BA', 'BLR': 'BY', 'BLZ': 'BZ', 'BOL': 'BO', 'BRA': 'BR',
    'BRB': 'BB', 'BRN': 'BN', 'BTN': 'BT', 'BWA': 'BW', 'CAF': 'CF',
    'CAN': 'CA', 'CHE': 'CH', 'CHL': 'CL', 'CHN': 'CN', 'CIV': 'CI',
    'CMR': 'CM', 'COD': 'CD', 'COG': 'CG', 'COL': 'CO', 'COM': 'KM',
    'CPV': 'CV', 'CRI': 'CR', 'CUB': 'CU', 'CYP': 'CY', 'CZE': 'CZ',
    'DEU': 'DE', 'DJI': 'DJ', 'DMA': 'DM', 'DNK': 'DK', 'DOM': 'DO',
    'DZA': 'DZ', 'ECU': 'EC', 'EGY': 'EG', 'ERI': 'ER', 'ESP': 'ES',
    'EST': 'EE', 'ETH': 'ET', 'FIN': 'FI', 'FJI': 'FJ', 'FRA': 'FR',
    'FSM': 'FM', 'GAB': 'GA', 'GBR': 'GB', 'GEO': 'GE', 'GHA': 'GH',
    'GIN': 'GN', 'GMB': 'GM', 'GNB': 'GW', 'GNQ': 'GQ', 'GRC': 'GR',
    'GRD': 'GD', 'GTM': 'GT', 'GUY': 'GY', 'HKG': 'HK', 'HND': 'HN',
    'HRV': 'HR', 'HTI': 'HT', 'HUN': 'HU', 'IDN': 'ID', 'IND': 'IN',
    'IRL': 'IE', 'IRN': 'IR', 'IRQ': 'IQ', 'ISL': 'IS', 'ISR': 'IL',
    'ITA': 'IT', 'JAM': 'JM', 'JOR': 'JO', 'JPN': 'JP', 'KAZ': 'KZ',
    'KEN': 'KE', 'KGZ': 'KG', 'KHM': 'KH', 'KIR': 'KI', 'KNA': 'KN',
    'KOR': 'KR', 'KWT': 'KW', 'LAO': 'LA', 'LBN': 'LB', 'LBR': 'LR',
    'LBY': 'LY', 'LCA': 'LC', 'LIE': 'LI', 'LKA': 'LK', 'LSO': 'LS',
    'LTU': 'LT', 'LUX': 'LU', 'LVA': 'LV', 'MAR': 'MA', 'MCO': 'MC',
    'MDA': 'MD', 'MDG': 'MG', 'MDV': 'MV', 'MEX': 'MX', 'MHL': 'MH',
    'MKD': 'MK', 'MLI': 'ML', 'MLT': 'MT', 'MMR': 'MM', 'MNE': 'ME',
    'MNG': 'MN', 'MOZ': 'MZ', 'MRT': 'MR', 'MUS': 'MU', 'MWI': 'MW',
    'MYS': 'MY', 'NAM': 'NA', 'NER': 'NE', 'NGA': 'NG', 'NIC': 'NI',
    'NLD': 'NL', 'NOR': 'NO', 'NPL': 'NP', 'NRU': 'NR', 'NZL': 'NZ',
    'OMN': 'OM', 'PAK': 'PK', 'PAN': 'PA', 'PER': 'PE', 'PHL': 'PH',
    'PLW': 'PW', 'PNG': 'PG', 'POL': 'PL', 'PRK': 'KP', 'PRT': 'PT',
    'PRY': 'PY', 'PSE': 'PS', 'QAT': 'QA', 'ROU': 'RO', 'RUS': 'RU',
    'RWA': 'RW', 'SAU': 'SA', 'SDN': 'SD', 'SEN': 'SN', 'SGP': 'SG',
    'SLB': 'SB', 'SLE': 'SL', 'SLV': 'SV', 'SMR': 'SM', 'SOM': 'SO',
    'SRB': 'RS', 'SSD': 'SS', 'STP': 'ST', 'SUR': 'SR', 'SVK': 'SK',
    'SVN': 'SI', 'SWE': 'SE', 'SWZ': 'SZ', 'SYC': 'SC', 'SYR': 'SY',
    'TCD': 'TD', 'TGO': 'TG', 'THA': 'TH', 'TJK': 'TJ', 'TKM': 'TM',
    'TLS': 'TL', 'TON': 'TO', 'TTO': 'TT', 'TUN': 'TN', 'TUR': 'TR',
    'TUV': 'TV', 'TWN': 'TW', 'TZA': 'TZ', 'UGA': 'UG', 'UKR': 'UA',
    'URY': 'UY', 'USA': 'US', 'UZB': 'UZ', 'VCT': 'VC', 'VEN': 'VE',
    'VNM': 'VN', 'VUT': 'VU', 'WSM': 'WS', 'YEM': 'YE', 'ZAF': 'ZA',
    'ZMB': 'ZM', 'ZWE': 'ZW',
  };
  final a2 = special[iso3];
  if (a2 == null) return '🌍';
  return String.fromCharCodes(a2.codeUnits.map((c) => 0x1F1E6 + c - 65));
}
