// Generates lib/catalog.dart for the BullDozer Flutter app from the site's dist/data/*.json
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DATA = join(process.env.HOME, 'Projects/bulldozer/dist/data');
const OUT = join(process.env.HOME, 'Projects/bulldozer_app/lib/catalog.dart');

// Same topic overrides as the site's lib/topics.ts TOPIC_OVERRIDES
const OVERRIDES = {
  'wrp-climate-threat': 'risk',
  'wrp-discrimination': 'risk',
  'wrp-worry-crime': 'risk',
  'wgm-vaccines-effective': 'attitudes',
  'wgm-vaccines-safe': 'attitudes',
};

const esc = (s) => String(s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$');

const files = readdirSync(DATA).filter(
  (f) => f.endsWith('.json') && !['country-index.json', 'quiz-pool.json'].includes(f)
);

const entries = [];
for (const f of files) {
  const j = JSON.parse(readFileSync(join(DATA, f), 'utf8'));
  if (!j.slug || !j.title || !Array.isArray(j.data)) continue;
  if (j.slug.startsWith('rlms-')) continue; // single-country microdata — not surfaced in the app
  const topic = OVERRIDES[j.slug] ?? j.topic ?? 'economy';
  entries.push({ slug: j.slug, title: j.title, unit: j.unit ?? '', kind: j.kind ?? 'macro', topic, source: j.source ?? '' });
}
entries.sort((a, b) => a.title.localeCompare(b.title));

const lines = entries.map(
  (e) => `  CatalogEntry('${esc(e.slug)}', '${esc(e.title)}', '${esc(e.unit)}', '${esc(e.kind)}', '${esc(e.topic)}', '${esc(e.source)}'),`
);

const dart = `// GENERATED by gen_catalog.mjs from the BullDozer site's dist/data — do not edit by hand.
// Regenerate: node gen_catalog.mjs (see README).
// This is the OFFLINE FALLBACK; at runtime the app loads the live catalog from
// /data/catalog.json (see catalog_store.dart).

class CatalogEntry {
  final String slug;
  final String title;
  final String unit;
  final String kind; // 'survey' | 'macro'
  final String topic;
  final String source;
  const CatalogEntry(this.slug, this.title, this.unit, this.kind, this.topic, this.source);
}

const List<CatalogEntry> bakedCatalog = [
${lines.join('\n')}
];
`;
writeFileSync(OUT, dart);
console.log(`${entries.length} datasets -> ${OUT}`);
